name: Clean Pull Request

on:
  pull_request:
    types: [opened, synchronize]
    branches:
      - main
      - test

jobs:
  update_pull_request:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Create target branch
      run: |
        source_branch=${{ github.event.pull_request.head.ref }}
        destination_branch=${{ github.event.pull_request.base.ref }}-clean
        git checkout -b $destination_branch $source_branch

    - name: Checkout specified files
      run: |
        git fetch origin ${{ github.event.pull_request.base.ref }}:$destination_branch
        git checkout $destination_branch
        git checkout origin/${{ github.event.pull_request.base.ref }} -- firebase.json src/Services/firebase-config.json src/Components/Navbar.jsx .github/workflows/firebase-hosting-merge.yml

    - name: Push changes
      run: |
        git add .
        git commit -m "Checkout specified files from ${GITHUB_BASE_REF}"
        git push origin $destination_branch

    - name: Update pull request
      uses: actions/github-script@v4
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        script: |
          const { owner, repo } = context.repo;
          const pr_number = context.payload.pull_request.number;
          const new_base = `${context.payload.pull_request.base.ref}-clean`;
          const octokit = github.getOctokit(process.env.GITHUB_TOKEN);
          await octokit.pulls.update({
            owner,
            repo,
            pull_number: pr_number,
            base: new_base
          });
